a=int(input("Enter the first number : "))
b=int(input("Enter the second number : "))
print("Value before swapping A = ",a)
print("Value before swapping B = ",b)
c=a
a=b
b=c
print("Value after swapping A =",a)
print("Value after swapping B =",b)
